name: Test SendGrid Email

on:
  workflow_dispatch:

jobs:
  send-test-email:
    runs-on: ubuntu-latest

    steps:
      - name: Send test email with curl
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          TO_EMAIL: ${{ secrets.TEST_TO_EMAIL }}
          FROM_EMAIL: ${{ secrets.TEST_FROM_EMAIL }}
        run: |
          curl --request POST \
            --url https://api.sendgrid.com/v3/mail/send \
            --header "Authorization: Bearer $SENDGRID_API_KEY" \
            --header "Content-Type: application/json" \
            --data '{
              "personalizations": [{
                "to": [{"email": "'"$TO_EMAIL"'"}],
                "subject": "✅ SendGrid Test from GitHub Actions"
              }],
              "from": {"email": "'"$FROM_EMAIL"'"},
              "content": [{
                "type": "text/plain",
                "value": "This is a test email sent via SendGrid through GitHub Actions."
              }]
            }'
